In [5]:
import numpy as np
from scipy import linalg

In [8]:
A = np.array([[1,2],[3,4]])
A

array([[1, 2],
       [3, 4]])

In [9]:
linalg.inv(A)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [10]:
b = np.array([[5,6]]) #2D array
b

array([[5, 6]])

In [11]:
b.T

array([[5],
       [6]])

In [12]:
A*b #not matrix multiplication!

array([[ 5, 12],
       [15, 24]])

In [13]:
A.dot(b.T) #matrix multiplication

array([[17],
       [39]])

In [14]:
b = np.array([5,6]) #1D array
b

array([5, 6])

In [15]:
b.T  #not matrix transpose!

array([5, 6])

In [6]:
A.dot(b)  #does not matter for multiplication

array([17, 39])

In [22]:
N = 4
a = np.random.rand(N,N)
b = np.ones((N,N+1))
#b
b[:,1:] = a
b

array([[ 1.        ,  0.05360692,  0.87640825,  0.35126924,  0.3515133 ],
       [ 1.        ,  0.69249379,  0.61028027,  0.39244883,  0.13055801],
       [ 1.        ,  0.83404539,  0.85414975,  0.80352316,  0.57906835],
       [ 1.        ,  0.34698005,  0.01109804,  0.74452359,  0.59176155]])

In [37]:
N = 4
a = np.random.rand(N,N)
b = np.zeros((N,1))
np.append(a,b,axis=1)

array([[ 0.89111306,  0.05280799,  0.10357646,  0.29696253,  0.        ],
       [ 0.32043331,  0.5691417 ,  0.18957082,  0.26848955,  0.        ],
       [ 0.37609124,  0.13430629,  0.14939412,  0.79008251,  0.        ],
       [ 0.52588862,  0.22660329,  0.21868043,  0.90008544,  0.        ]])