In [2]:
import numpy as np

In [17]:
a1 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
print(a1)
print(a1[1:7:2])

a2 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(a2)
print(a2[1,:])
print(np.sum(a2, axis=0))

[1 2 3 4 5 6 7 8 9]
[2 4 6]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[4 5 6]
[12 15 18]
