In [77]:
import numpy as np
import math

In [37]:
# Bubble sort

def bubbleSort(data):
    unsortedLength = len(data)
    swapped = True
    while swapped:
        swapped = False
        for i in range(1,unsortedLength):
            if data[i-1] > data[i]:
                swapped = True
                temp = data[i-1]
                data[i-1] = data[i]
                data[i] = temp
        unsortedLength = unsortedLength - 1   
                

data = np.random.randint(10, size=10)
print (data)
bubbleSort(data)
print (data)

[1 0 4 1 0 7 5 4 9 3]
[0 0 1 1 3 4 4 5 7 9]


In [81]:
# Merge sort

def merge(data, iStart, iMiddle, iEnd):
    mergedData = []
    i1 = iStart
    i2 = iMiddle
    while i1 < iMiddle or i2 < iEnd:
        if i2 == iEnd or (i1 < iMiddle and data[i1] < data[i2]):
            mergedData.append(data[i1])
            i1 += 1
        else:
            mergedData.append(data[i2])
            i2 += 1

    data[iStart:iEnd] = mergedData

def mergeSort(data, iStart=None, iEnd=None):
    iStart = iStart if iStart else 0
    iEnd = iEnd if iEnd else len(data)
    if iEnd - iStart < 2:
        return data[0]
    else:
        iMiddle = math.ceil(iStart + ((iEnd - iStart) / 2))
        mergeSort(data, iStart, iMiddle)
        mergeSort(data, iMiddle, iEnd)
        merge(data, iStart, iMiddle, iEnd)


data = np.random.randint(10, size=10)
print(data)
mergeSort(data)
print(data)

[2 9 3 9 0 7 0 7 4 4]
[0 0 2 3 4 4 7 7 9 9]


In [ ]:
# Heap sort

def calc_i_left_child(i):
    return 2 * i + 1

def calc_i_right_child(i):
    return calc_i_left_child(i) + 1

# swap parent with the biggest child
def sift_down(data, iParent, iEnd):
    i_left_child = calc_i_left_child(iParent)
    i_right_child = calc_i_right_child(iParent)

    i_biggest_child = None
    if i_left_child < iEnd and (i_right_child >= iEnd or data[i_left_child] > data[i_right_child]):
        i_biggest_child = i_left_child
    elif i_right_child < iEnd:
        i_biggest_child = i_right_child

    if i_biggest_child and data[iParent] < data[i_biggest_child]:
        temp = data[iParent]
        data[iParent] = data[i_biggest_child]
        data[i_biggest_child] = temp
        sift_down(data, i_biggest_child, iEnd)

def heapify(data, iParent, iEnd):
    if (iParent < iEnd):
        heapify(data, calc_i_left_child(iParent), iEnd)
        heapify(data, calc_i_right_child(iParent), iEnd)
        sift_down(data, iParent, iEnd)

def heapSort(data):
    i_end_unsorted = len(data)
    heapify(data, 0, i_end_unsorted)
    while i_end_unsorted > 0 and data[0] > data[i_end_unsorted - 1]:
        temp = data[0]
        data[0] = data[i_end_unsorted - 1]
        data[i_end_unsorted - 1] = temp
        i_end_unsorted -= 1
        heapify(data, 0, i_end_unsorted)

data = np.random.randint(10, size=10)
print(data)
heapSort(data)
print(data)