In [77]:
import numpy as np
import math

In [37]:
# Bubble sort

def bubbleSort(data):
    unsortedLength = len(data)
    swapped = True
    while swapped:
        swapped = False
        for i in range(1,unsortedLength):
            if data[i-1] > data[i]:
                swapped = True
                temp = data[i-1]
                data[i-1] = data[i]
                data[i] = temp
        unsortedLength = unsortedLength - 1   
                

data = np.random.randint(10, size=10)
print (data)
bubbleSort(data)
print (data)

[1 0 4 1 0 7 5 4 9 3]
[0 0 1 1 3 4 4 5 7 9]


In [80]:
# Merge sort
def merge(data, iStart, iMiddle, iEnd):
    mergedData = []
    i1 = iStart
    i2 = iMiddle
    while i1 < iMiddle or i2 < iEnd:
        if i2 == iEnd or (i1 < iMiddle and data[i1] < data[i2]):
            mergedData.append(data[i1])
            i1 += 1
        else:
            mergedData.append(data[i2])
            i2 += 1

    data[iStart:iEnd] = mergedData

def mergeSort(data, iStart=None, iEnd=None):
    iStart = iStart if iStart else 0
    iEnd = iEnd if iEnd else len(data)
    if iEnd - iStart < 2:
        return data[0]
    else:
        iMiddle = math.ceil(iStart + ((iEnd - iStart) / 2))
        mergeSort(data, iStart, iMiddle)
        mergeSort(data, iMiddle, iEnd)
        merge(data, iStart, iMiddle, iEnd)


data = np.random.randint(10, size=10)
print(data)
mergeSort(data)
print(data)

[1 1 3 4 4 2 7 6 8 2]
[1 1 2 2 3 4 4 6 7 8]
