In [1]:
import numpy as np
a1 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
a2 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [2]:
print(a1)

[1 2 3 4 5 6 7 8 9]


In [3]:
print(a1[1:7:2])

[2 4 6]


In [4]:
print(a2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [5]:
print(a2[1,:])

[4 5 6]


In [6]:
print(np.sum(a2, axis=0))

[12 15 18]
